
import javax.swing.JFrame;



/**
 *
 * @author EMON KABIR
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStudent_btn = new javax.swing.JButton();
        AddBook_btn = new javax.swing.JButton();
        Statistics_btn = new javax.swing.JButton();
        Issue_btn = new javax.swing.JButton();
        return_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddStudent_btn.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        AddStudent_btn.setText("Add Student");
        AddStudent_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudent_btnActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudent_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 50, 124, 33));

        AddBook_btn.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        AddBook_btn.setText("Add Book");
        AddBook_btn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                AddBook_btnAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        AddBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBook_btnActionPerformed(evt);
            }
        });
        getContentPane().add(AddBook_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 50, 121, 33));

        Statistics_btn.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        Statistics_btn.setText("Statistics");
        Statistics_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Statistics_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Statistics_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 50, 112, 33));

        Issue_btn.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        Issue_btn.setText("Issue Book");
        Issue_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Issue_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Issue_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 50, 130, 33));

        return_btn.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        return_btn.setText("Return Book");
        return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btnActionPerformed(evt);
            }
        });
        getContentPane().add(return_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 128, 33));

        logout_btn.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        logout_btn.setText("Log Out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 50, 130, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon("H:\\book-club-image.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void AddStudent_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudent_btnActionPerformed
        // TODO add your handling code here:
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_AddStudent_btnActionPerformed

    private void AddBook_btnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_AddBook_btnAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddBook_btnAncestorAdded

    private void AddBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBook_btnActionPerformed
        // TODO add your handling code here:
        new AddBook().setVisible(true);
    }//GEN-LAST:event_AddBook_btnActionPerformed

    private void Issue_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Issue_btnActionPerformed
        // TODO add your handling code here:
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_Issue_btnActionPerformed

    private void return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btnActionPerformed
        // TODO add your handling code here:
        new ReturnBook().setVisible(true);
    }//GEN-LAST:event_return_btnActionPerformed

    private void Statistics_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Statistics_btnActionPerformed
        // TODO add your handling code here:
        new Statistics().setVisible(true);
    }//GEN-LAST:event_Statistics_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook_btn;
    private javax.swing.JButton AddStudent_btn;
    private javax.swing.JButton Issue_btn;
    private javax.swing.JButton Statistics_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton return_btn;
    // End of variables declaration//GEN-END:variables
}
